# /opt/ansible/add_infra_sudo_append.yml
- hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Ensure sudoers.d exists
      ansible.builtin.file:
        path: /etc/sudoers.d
        state: directory
        mode: '0750'

    - name: Ensure infra passwordless sudo line is present (append if missing)
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/90-cloud-init-users
        line: 'infra ALL=(ALL:ALL) NOPASSWD:ALL'
        state: present
        create: yes
        mode: '0440'
        owner: root
        group: root
        validate: 'visudo -cf %s'
